#!/bin/bash

echo "I am week_day1" > week_day1
echo "I love being Monday" >> week_day1

echo "I am week_day2" > week_day2
echo "I love being Tuesday" >> week_day2

echo "I am week_day3" > week_day3
echo "I love being Wednesday" >> week_day3

echo "I am week_day4" > week_day4
echo "I love being Thursday" >> week_day4

echo "I am week_day5" > week_day5
echo "I love being Friday" >> week_day5

echo "week_day1:"
echo "$(cat week_day1)"
echo "%%%%%%%%%%%%%%%%%%%"
echo "week_day2:" 
echo "$(cat week_day2)"
echo "%%%%%%%%%%%%%%%%%%%"
echo "week_day3:" 
echo "$(cat week_day3)"
echo "%%%%%%%%%%%%%%%%%%%"
echo "week_day4:" 
echo "$(cat week_day4)"
echo "%%%%%%%%%%%%%%%%%%%"
echo "week_day5:"
echo "$(cat week_day5)"  
echo "%%%%%%%%%%%%%%%%%%%"   

echo "$(cat week_day3)" >> Weekdays
echo "$(cat week_day5)" >> Weekdays
echo "$(cat week_day1)" >> Weekdays
echo "$(cat week_day2)" >> Weekdays
echo "$(cat week_day4)" >> Weekdays

echo "Weekdays:"
echo "$(cat Weekdays)"

echo "$(ls -la)"

rm week_day1 week_day2 week_day3 week_day4 week_day5 Weekdays

echo "$(ls -la)"
